### ISSUE TITLE
Доступ к картинке.

### ISSUE THREAD

**Issue by hotrush** [modanets/s3thumb#1]
Допустим я сгенерил ссылку и создал на амазоне по ней превьюху. Как мне в дальнейшем получить к ней доступ. Или как проверить существует ли такая тумба на с3.

**Comment by modanets** [comment]
Давайте по порядку.
1) создать на amazon s3 бакет(ы)
2) настроить редирект на Ваш сервер
3) настроить поддомен(ы)

На Вашем сайте будет использоваться всего 2 метода класса CS3Thumb:
 -> url - для формироания ссылки
 -> process - собственно он и делает все сам - создает миниатюру и кладет ее на s3

Первый метод - вызывайте там, где выводятся картинки:
< h t m l >
...
< i m g  s r c="<?= $Thumb -> url("http://blablabla.com/photo15.jpg", 100, 100) ?>" / >
...
< h t m l >

а второй метод - на том скрипте, куда направлен редирект с амазона.

Вам не нужно ничего проверять. Класс все сделает сам. В методе url и process используются одна и таже функция формирования ссылки. Т.е. когда метод url вызывается - он понятия не имеет есть ли на амазоне миниатюра или нет. Ему и не нужно этого знать. Он просто формирует ссылку по одному и тому-же алгоритму каждый раз.

Надеюсь правильно понял вопрос.

**Comment by hotrush** [comment]
понял, невнимательно читал про редиректы, прошу прощения. интересное решение.

Есть пара мучающих меня вопросов по s3, если можете проконсультировать напишите плз johny64@gmail.con
